# Generated by Django 3.2.6 on 2021-10-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attack', models.IntegerField(max_length=10)),
                ('life', models.IntegerField(max_length=100)),
                ('origin', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobstack',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobstack',
            name='stack',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobStack',
        ),
        migrations.DeleteModel(
            name='Stack',
        ),
    ]
