# Generated by Django 3.2.6 on 2021-10-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20211020_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='attack',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='life',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
